### ISSUE TITLE
Don't auto switch to desktop n

### ISSUE THREAD

**Issue by gkovacsds** [eksime/VDesk#10]
It would be very great option if the launched app did not switch to its desktop - so I could launch apps as background tasks on desktop N.
Or if it's not possible, could VDesk switch back to current desktop?

I mean 
1 - get current desktop number A
2 - launch app
3 - wait until app has created its window and desktop B activates
4 - switch back to desktop A

Now I can make a workaround by calling vdesk twice, performing step 3 inbetween with another piece of software, then calling a dummy app for desktop A in step 4. Still, the taskbar contains the app of desktop B on desktop A, but it's no problem. The flash of switching desktops is more annoying.

Thanks for this must have (for me) software!

**Comment by t-p-l-k** [comment]
Yeah, it'll be a great feature.

**Comment by t-p-l-k** [comment]
Will try to implement and inform you if I succeed.

**Comment by eksime** [comment]
This has been fixed in 6f19ad6f9389b3a1ddb87d19b2d95e0efd210e32 switching to the desktop where the app is launched is no longer the default.
