### ISSUE TITLE
VDesk and VirtualDesktopManager Stopped Working Win 10 Build 14372

### ISSUE THREAD

**Issue by BigXmasGuy** [eksime/VDesk#11]
Everything worked great at win 10 Build 10586.420 but I started to have problems as the builds advanced, I'm now at 14372..
The screen blinks but no virtual desktop is created nor is the application opened.  For example
 VDesk 2 "C:\Paul's Prog & BAT & Shortcuts\bat files\Zimbra Desktop"
where Zimbra Desktop is a shortcut.

VirtualDesktopManager appears to run and puts an icon in the Taskbar area but when you mouse-over it disappears.
Really like your tools so I hope the Windows build does not require many changes.

**Comment by eksime** [comment]
I'll get the latest insider build downloaded and test on my surface when I
can. Between work and exams I dont have much time to work on stuff right
now.
Thanks.

**Comment by BigXmasGuy** [comment]
I Understand.  I only have one out of 8 of my machines on the insider fast track so time is not important.

Thanks, Paul

----- Original Message -----

**Comment by SuperITMan** [comment]
Hello,
Today I discovered your project and I found the idea awesome ! :)
Unfortunately, this does not work on my PC on build 14393.51 ... 

Any idea how to fix it ?

Thank you for the project

**Comment by ChipRab** [comment]
It also is not working on 14393.187, the release version.  Sure wish I could get it working again, I miss it!

**Comment by phkrug** [comment]
I've discovered that the GUID of one of the use COM-objects (IVirtualDesktopManagerInternal) has changed with the Anniversary Update. There are some other projects that use this interface for interaction with the virtual desktops, that seem to not have that issue. Although I changed the GUIDs in the code and compiled it myself, it won't work. So it seems that there is another issue besides the changed GUIDs. I don't have any experience with C# so it's kinda hard to figure out what's wrong. But I'd like to contribute to this project as soon as this very issue is fixed. :)

**Comment by eksime** [comment]
Thanks for the info! unfortunately Its the area I know least about. I'll
take a look sometime soon as a few people seemed to actually use this, but
I'm busy moving house right now

**Comment by ChipRab** [comment]
I wish I had time to work with this....I know C# and COM pretty well, just time is my issue to get it all downloaded and working......sigh.  Would *love* to combine this utility with the other one I use all the time:  https://github.com/m0ngr31/VirtualDesktopManager.  Anyone out there with time to work with it?

**Comment by eksime** [comment]
Looks like @Grabacr07 has a NuGet package available which is an updated version of the code used to manage desktops!
I'll take a look later tonight if I get chance.

**Comment by phkrug** [comment]
I guess there is some refactoring coming your way. With this package you can leave the management of the virtual desktops to the code of the said package and focus on what you want to do within your own app. That seems like a pretty decent and clean solution to me.

**Comment by eksime** [comment]
Yep, I'm in the process of that now. The new package isn't playing nice with the program not having either a windows form or a wpf window though, keeps throwing errors either when I try to create a desktop or exit the program. I'd been meaning to add a gui to "install" / "uninstall" the registry keys and to help run the program as a daemon/service type thing to listen for switch desktop events so that some of the requested features could be implemented... along with better command line handling. I think I'm just going to start again, but it looks like I'll have to go with a hidden WPF window to get it to work for now.

**Comment by eksime** [comment]
Ok, as of 6f19ad6f9389b3a1ddb87d19b2d95e0efd210e32 it's working in the latest win 10 build.
Still can't figure out how to use the nuget library without a form/window though :(
