### ISSUE TITLE
Command Line Args not Working

### ISSUE THREAD

**Issue by BuGBeN** [eksime/VDesk#12]
The command line args s not working.
The command:

`vdesk 3 notepad "C:\some file.txt"`

opens the notepad, but ignores the "C:\some file.txt" arg.

The problem is in Program.cs, line 97:
`   for (int i = 1; i < 4; i++)`

I changed it to the following to correct it:
`   for (int i = 1; i < 5; i++)`

**Comment by eksime** [comment]
Thanks, fixed in bb2d97a34d60cd3aa698b8c16c1f5caeb82433ab
