### ISSUE TITLE
Quoted command-lines do not work correctly

### ISSUE THREAD

**Issue by ChipRab** [eksime/VDesk#13]
The following command-line does not work:

vdesk 5 "C:\Program Files (x86)\VMware\VMware Workstation\vmware.exe" -n "F:\My VMware Machines\Chip Development\Simple-XPSP2.vmx"

VMWare starts correctly.....but it doesn't get the additional argument.....so my VM doesn't open correctly.

**Comment by eksime** [comment]
This should be fixed as of 6f19ad6f9389b3a1ddb87d19b2d95e0efd210e32 
The syntax for the commandline has changed slightly, 

`vdesk 5 "C:\Program Files (x86)\VMware\VMware Workstation\vmware.exe" -n "F:\My VMware Machines\Chip Development\Simple-XPSP2.vmx"`

would now be

`vdesk run-on-switch 5 "C:\Program Files (x86)\VMware\VMware Workstation\vmware.exe" -n "F:\My VMware Machines\Chip Development\Simple-XPSP2.vmx"`
