### ISSUE TITLE
SHIM_NOVERSION_FOUND

### ISSUE THREAD

**Issue by michaelcrossland** [eksime/VDesk#14]
Okay I have tried your new update but every time I try to run it be it from the CML or a batch file or even a desktop shortcut I get this popup that windows puts up.
Error: "This application could not be started"
Then i get asked if I want to got Microsoft KB web page.
Here is what it says about the popup I keep getting.

Error: "This application could not be started"
Error message
This application could not be started.
Cause
The app is not configured in a way that makes it possible to determine the appropriate version of the .NET Framework runtime. The corresponding shim code is SHIM_NOVERSION_FOUND.
Resolution
You can't fix the configuration problem yourself. Contact the app vendor to resolve the issue.

That comes from there page here. [https://support.microsoft.com/en-us/kb/2715633](url)
maybe you cold look into this and help getting it to work.
Thanks for all our hard work,
Michael

**Comment by eksime** [comment]
The program should be marked as requiring .NET 4.6, I'll double check that it's building correctly.

In the meantime, you should be able to install [Microsoft .NET Framework 4.6.2](https://www.microsoft.com/en-us/download/details.aspx?id=53344) to get it working

**Comment by michaelcrossland** [comment]
Thank you for looking into this asap. I have got it working now and liking
it just wish Playon.exe would play nice your program will open that exe
just fine even make new desktop for it but the app keeps opening in what
ever desktop I am in when I try to run the command be from the CML or from
a desktop shortcut. But I don't think it's your apps doing, I think it that
Playon exe that is doing it. As the Playon server settings exe works just
fin with you vdesk. Keep up the good work once I have gotten some money
here in the next 2 or 3 weeks I will try to see if you have a way for me to
donate to you for this app.
Thanks for your time,
Michael

**Comment by eksime** [comment]
I am working on an alternate way to launch programs on certain desktops:
At the moment vdesk creates a new desktop, then launches the program you want to run, and moves it to a specific desktop by waiting until it's main window handle is not null. Some programs have strange startup behavior, and continue to launch on the "current" desktop.

I'm also not sure I can accept donations as most of the "hard" development was done by Grabacr07 (see; https://github.com/Grabacr07/VirtualDesktop) and this program wouldn't be possible without it, but the offer was appreciated :)
