### ISSUE TITLE
Multiple VDesk processes using abnormal amount of CPU resources

### ISSUE THREAD

**Issue by hylkepostma** [eksime/VDesk#17]
This is a great tool. Thanks for that! 
However, I found an issue I would like to report.

## Environment
Windows 10 (Anniversary Update) on Asus UX305 (i5, 8GB RAM) using latest VDesk (0.2-beta1)
VDesk in my Windows PATH

## Set-up
2 pinned programs (Whatsapp and Spotify) in taskbar (shortcuts) are using VDesk like this in Target:
vdesk run-on-switch 2 [path_to_app_folder]\WhatsApp.exe

![target](https://cloud.githubusercontent.com/assets/20515386/20308733/8cab5468-ab45-11e6-80bf-72e12381a196.PNG)

## Issue
Every time I use one of the shortcuts it starts a new (heavy) VDesk process (using up to 25% CPU) which keeps running (until I end the task manually). So after a while all of my CPU is used by VDesk. Check it out:

![resources](https://cloud.githubusercontent.com/assets/20515386/20308849/ec59c11a-ab45-11e6-96ad-654c0194514f.PNG)

**Comment by eksime** [comment]
This should be fixed in the latest release.
