### ISSUE TITLE
Run-on-switch not launching in correct desktop

### ISSUE THREAD

**Issue by PraiseSatan** [eksime/VDesk#20]
The run-on-switch command (as far as I can tell, and what the code suggests) doesn't launch the application in the correct desktop. Instead it launches in the last desktop.
So if you have 4 desktops running and execute something like:
`vdesk run-on-switch 2 winword`
the application (microsoft word in this case) will open on the 4th desktop.
I think this is because you are returning the last desktop in createMaxDesktops and thus it is switching to that.
would it break anything to have that return something like:
`VirtualDesktop.GetDesktops()[n - 1];`
instead of 
`VirtualDesktop.GetDesktops().Last();`

The only thing I could think of is if you wanted to be able to switch to the last desktop after creating at least n.

**Comment by eksime** [comment]
Fixed in pull request e251709456a9cac3a1224015f1a8556d7064b7bc
