### ISSUE TITLE
running the exe via command line does not do anything.

### ISSUE THREAD

**Issue by HaswinVidanage** [eksime/VDesk#26]
running the exe via command line does not do anything.

OS : Windows 10 Home Single Language 64 bit

**Comment by Xrayez** [comment]
What do you mean by installing? VDesk executable is supposed to be run via command line AFAIK.

**Comment by HaswinVidanage** [comment]
@Xrayez  yes sorry my bad wrong term. updated the issue.

**Comment by HaswinVidanage** [comment]
found out that bitdifender was blocking the exe. No issue.
