### ISSUE TITLE
Running certain programs returns error

### ISSUE THREAD

**Issue by Rimbaldo** [eksime/VDesk#27]
Hi! I tried using vdesk in a batch file (and in command-line too) to run excel on virtual desktop 2. It starts excel and immediatelly gives an dialog box with an error saying that vdesk had to be closed. But excel opens. Anyone noticed this also?  I'm over Win 10 X64 enterprise with office 2016...

Great software btw!

**Comment by eksime** [comment]
The error appears to be related to the way vdesk handles threads and the
way the program closes. This wasn't an issue originally, so I can only
assume that something has changed in a recent windows update.

Is it only certain programs launched via vdesk you receive the error
message on, or all programs?

I'm starting to work on vdesk a little now that I have (some) spare time,
and I'm aiming to fix the remaining bugs in this version, alongside
releasing a GUI version that will hopefully fix many of the issues / help
requests that people email me with.

-Elliot


On 29 Apr 2017 11:16 pm, "Rimbaldo" <notifications@github.com> wrote:

Hi! I tried using vdesk in a batch file (and in command-line too) to run
excel on virtual desktop 2. It starts excel and immediatelly gives an
dialog box with an error saying that vdesk had to be closed. But excel
opens. Anyone noticed this also? I'm over Win 10 X64 enterprise with office
2016...

Great software btw!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eksime/VDesk/issues/27>, or mute the thread

**Comment by Rimbaldo** [comment]
Sorry, I thought gmail would compress the pictures. I´ll send them later..
I formatted my computer and have to locate my picresize software...



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-04-30 8:05 GMT-03:00 Elliot Sime <notifications@github.com>:

> The error appears to be related to the way vdesk handles threads and the
> way the program closes. This wasn't an issue originally, so I can only
> assume that something has changed in a recent windows update.
>
> Is it only certain programs launched via vdesk you receive the error
> message on, or all programs?
>
> I'm starting to work on vdesk a little now that I have (some) spare time,
> and I'm aiming to fix the remaining bugs in this version, alongside
> releasing a GUI version that will hopefully fix many of the issues / help
> requests that people email me with.
>
> -Elliot
>
>

**Comment by Rimbaldo** [comment]
Hi! Thanks for your quick answer.
>
> So far only Word and Excel act this way..
>
> I tried different scenarios and I found one another bug..
>
> I created 2 more desktops, opened some softwares (Photoshop (on 2) ,
> notepad (on 2) , my dental management software (on 3), and tried to open
> Firefox on Desktop 1 and switch to it (on 1). Firefox opened on desktop 3:
>
> Hope this helps!
>
> Cheers, Rodrigo
>
> Pics below:
>
> This is the error with Word and Excel
>
>
> My test.bat:
>
>
>
> Desktop 2 is correct..
>
>
>
> But Desktop 3 should have only my dental manager and 1 should have
> Firefox... Firefox is on 3...
>
>
> ​
>
>
> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> Virus-free.
> www.avast.com
> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
> <#m_8649489356425736386_m_5926705277416590402_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>

**Comment by eksime** [comment]
Hi, just uploaded a new version. It has quite a few changes. 
Unfortunately I do not have access to office to test locally, can you try the new release to see if it's fixed.

Be aware there have been some changes to the command line syntax for vdesk, for info check the readme.

**Comment by Rimbaldo** [comment]
Hi! I´m unable to test de file right now... Avast keeps telling me the file was sent to avast Labs for analysis, because is seems suspicious, and in a couple of hours they´ll have an answer, and locks the file for execution... But they never finish the analysis. Can you confirm it´s safe, and there´s nothing accidentally attached to it? So I can disable Avast and test it? Thanks!

**Comment by eksime** [comment]
Hi There,
As far as I am aware the files are safe.

You can view the VirusTotal results for the two files (VDesk.exe  and VDeskSetup-1.0.2) [here](https://www.virustotal.com/en/file/de70699af05f902994577759146c9964aa91da6e78e36270ee331ba333731da4/analysis/1493999167/) and [here](https://www.virustotal.com/en/file/3b973f93b9c1d4b44dd9738ac1c06baae051fa4a47ad0d5bead944e1bf8ef7eb/analysis/1493999213/) respectively.

If you're concerned about security you could download the source and inspect it before compiling it yourself. It builds easily under VS2015 / VS2017 as there are very few dependencies (all of which are included, apart from the [Windows Installer](http://wixtoolset.org/) toolset, which is not required unless you want to build the .msi)

-Elliot

**Comment by Rimbaldo** [comment]
Hi! I´ve just tested..
Excel and Word open normally, no errors, but...

The argument switch:true returns an error, like true isn´t a recognized word.  switch:false doesn´t return an error, but makes no difference. The program run gets switched to.

Also. when I created 3 desktops:

vdesk.exe create:3
vdesk.exe on:2 switch:false run:"C:\Program Files (x86)\Microsoft Office\Office16\Excel.exe"
vdesk.exe on:3 switch:false run:"C:\Program Files (x86)\Microsoft Office\Office16\Winword.exe"

Excel and Word both go to the third one, not one in the second and one in the third. Also, the switch:false makes no difference.

If I run like this:
vdesk.exe create:3
vdesk.exe on:3 switch:false run:"C:\Program Files (x86)\Microsoft Office\Office16\Excel.exe"
REM vdesk.exe on:3 switch:false run:"C:\Program Files (x86)\Microsoft Office\Office16\Winword.exe"

Excel runs on the third desktop correctly, but gets switched to.

So far this is what I´ve seen. 

Hope this helps!

**Comment by eksime** [comment]
Hi,

The `switch` command is actually `noswitch:true` or `noswitch:false`
Where `noswitch:true` prevents switching.

I may add `switch` as a negated alias to `noswitch` in the future to avoid confusion.

As for microsoft office programs launching on the same desktops, try the code outlined here: https://github.com/eksime/VDesk/issues/30#issuecomment-299746372

Additionally the `vdesk create:3` at the start of the script is not needed, as the call to `on:3` will create 3 desktops automatically.
