### ISSUE TITLE
Window popups need to click ok to continue.

### ISSUE THREAD

**Issue by cruzer619** [eksime/VDesk#29]
First off great app, much needed for a better experience.  Everything is working fine so far on 1.0.1 but everytime I launch vdesk keeps bringing up a dialog box of the said command.  Almost like a verify, press ok and it does what its suppose to.  Is this by design or am I missing something.  I am running this via batch file.

Thanks
Richie

**Comment by cruzer619** [comment]
![capture20](https://cloud.githubusercontent.com/assets/26581299/25690819/0a652698-304a-11e7-8792-a4049c460347.PNG)

**Comment by eksime** [comment]
Fixed by 41c38e50c45f8e8f817f33a3e8f1c3abf33e4dbe
Updated executable and installer posted to releases.

**Comment by cruzer619** [comment]
Thanks.. much better.

Richie
