### ISSUE TITLE
Publish a  VDesk Chocolatey package

### ISSUE THREAD

**Issue by thatfrankdev** [eksime/VDesk#31]
Great project, thanks for that! 👍 

It would be awesome to have it as a [Chocolatey](https://chocolatey.org/packages?q=vdesk) package, so people could include VDesk in their [Boxstarter ](http://boxstarter.org/) scripts and such.

Cheers!

**Comment by eksime** [comment]
Thanks for the interest!

I've submitted the package for approval:
https://chocolatey.org/packages/vdesk

**Comment by thatfrankdev** [comment]
Awesome, thanks!

**Comment by mzomparelli** [comment]
This package was rejected on 6/13/2017. The reviewer chocolatey-ops has listed the following reason(s): 
eksime (maintainer) on 08 May 2017 19:38:20 +00:00:

User 'eksime' (maintainer) submitted package.

chocolatey-ops (reviewer) on 08 May 2017 20:12:12 +00:00:

vdesk has failed automated validation.
