### ISSUE TITLE
Switch to desktop without opening an application

### ISSUE THREAD

**Issue by authorleon** [eksime/VDesk#36]
Hello, 

Is it possible to switch to a desktop with opening an application. 

For example: `vdesk 3`

When I try this, well I get a popup. 

Thanks

**Comment by authorleon** [comment]
Anyone please?

**Comment by eksime** [comment]
I've been unable to work on vdesk for the last couple of months due to moving. I'll work on re-adding the ability to switch to a desktop without opening a program. It should be a fairly fast fix.

**Comment by authorleon** [comment]
Thank you very much. 

 

At the moment, I have this code with hotkey to make it work. Not the best but it works, most of the time:

 

;<<<<<<<<<< NUMPAD 3 >>>>>>>>>>>>>>>

NUMPAD3::

dhw := A_DetectHiddenWindows

DetectHiddenWindows On

Run "%ComSpec%" /k,, Hide, pid

while !(hConsole := WinExist("ahk_pid" pid))

             Sleep 10

DllCall("AttachConsole", "UInt", pid)

DetectHiddenWindows %dhw%

objShell := ComObjCreate("WScript.Shell")

objExec := objShell.Exec("cmd /c vdesk on:3 run:rundll32""")

While !objExec.Status

    Sleep 100

strLine := objExec.StdOut.ReadAll() ;read the output at once

;msgbox % strLine

DllCall("FreeConsole")

Process Exist, %pid%

if (ErrorLevel == pid)

Process Close, %pid%

return

;<<<<<<<<<< NUMPAD 3 >>>>>>>>>>>>>>>

**Comment by eksime** [comment]
new MSI will be available soon.

Please uninstall the older version, and add the new directory under program files to the system path.

**Comment by authorleon** [comment]
Great, I will give it ago. Would the command be: vdesk on:3

**Comment by eksime** [comment]
MSI available at : https://github.com/eksime/VDesk/releases/tag/v1.1.0

The command would be `vdesk 3` for compatibility, though I may add support for `vdesk on:3` too.

**Comment by authorleon** [comment]
Thank you, works perfectly. 

 

Just to let you know I had to copy the file to C:\Winodws in order for in to work in the CMD.

 

Thank you
