### ISSUE TITLE
Running a metro app

### ISSUE THREAD

**Issue by thany** [eksime/VDesk#37]
This doesn't seem possible. The recommended way of starting a metro app, as far as I can tell, is, for example:
```
start wunderlist:
```
Work fine.
So I should be able to do:
```
vdesk on:2 run:start wunderlist:
```
That gives me an Open With dialog (on desktop 2, so that bit works) asking me what program to open `start` with, presumably.
Another try then:
```
vdesk on:2 run:"start wunderlist:"
```
This gives the error `the system cannot find the file specified`

Tested on Windows 10 x64 with Fall Creators update.

**Comment by eksime** [comment]
Hi There,

You should be able to just do `run:wunderlist:`

Let me know if that works or not

**Comment by cruzer619** [comment]
Nice...  I never could figure out to make that work..  I"ve always used a batch script to do this with vdesk.  Makes things much cleaner now.

Thanks  :)

**Comment by thany** [comment]
Running an app like that certainly works :)
But now when I do this:
```
vdesk on:2 noswitch:true run:wunderlist:
```
The app does start, but on VD1 (VD2 exists just fine) and vdesk displays this error:

![capture](https://user-images.githubusercontent.com/152227/31989218-f3849f4c-b971-11e7-85d1-a641ce2e5424.PNG)

**Comment by cruzer619** [comment]
thany,  try the batch way that I was doing previous.  Make a batch file say in c:\scripts\wunderlist.bat  and inside the batch file will be "start wunderlist:" without quotes.  Then on your vdesk command will be "vdesk on:2 noswitch:true run:"c:\scripts\wunderlist.bat"

See if that works.

**Comment by eksime** [comment]
Running UWP apps should work using the protocol handler method (like `vdesk run:calculator:` or `vdesk run:wunderlist:`), although noswitch:true is broken, as detailed in #54
