### ISSUE TITLE
Startup directory

### ISSUE THREAD

**Issue by thany** [eksime/VDesk#38]
Can an option be added to have an application start up in a specific direct, or at least set it to the directory where its exe is located?

Certain programs need to have this parameter filled out properly. This is the same as the "Start in" field in the properties of a shortcut.

For example, if I start HipChat:
```
vdesk on:2 noswitch:true run:"C:\Program Files (x86)\Atlassian\HipChat4\HipChat.exe"
```
The program complains about not being able to find most of its own core dlls. This is very likely because the startup directory for the process is incorrect.

**Comment by eksime** [comment]
Fixed in 409fd8efd0ae77b3741b7c31ef1f57d0295d3aa2
