### ISSUE TITLE
Error when trying to run `.lnk` file

### ISSUE THREAD

**Issue by siddhantrimal** [eksime/VDesk#42]
I am trying to run `Visual Studio 2015`, and for various reasons, I'm unable to target the correct version of VS to open up(_I have multiple versions of VS_) with the command `devenv`.

Normally, `devenv` is supposed to open the latest version of VS installed in the computer. 

So, as a quick workaround, I created `devenv2015.lnk` and set the `Environment Variable` to the path. It works flawlessly on RUN and direct Powershall/CMD but on `vdesk` , its behaving poorly.

![vdesk-behaves-poorly-with-lnk](https://user-images.githubusercontent.com/18209220/32557978-cc3ede1a-c4cb-11e7-8833-769a956c08c2.PNG)

#  The Issue is

The last vdesk commands doesn't run at all when I use `.lnk` just before it.

```
vdesk create:3
vdesk on:1 run:slack
vdesk on:2 noswitch:true run:devenv2015.lnk
vdesk on:3 noswitch:true run:sublime_text
exit
```
It runs(and sometimes doesn't) rather unreliably when I change the order so that `.lnk` starts last.
 
> Just drawing your attention to this because it might be something that causes related problems.

**Comment by siddhantrimal** [comment]
**Update**
![](https://i.imgur.com/ZmeadmX.png)
I realized this today, but when all those times `vdesk on:2 run:devenv2015.lnk` was running successfully, it was probably passing context from powershell(_or straightout exiting powershell due to inability of handling some kind of error_). I am unsure if it is the case from the RUN command(`Win+R`) too.
> What happens is: The command runs and opens VS2015 successfully, but immediately closes the powershell window. This is probably whats causing consecutive commands to not register.

**Comment by siddhantrimal** [comment]
I just tried this shoddy workaroud _and it runs flawlessly on cmd.exe(_ ___just not powershell ;wcyd___ 🤷‍♂️ _)_ 

```
start /i /w vdesk create:3

ping -n 2 127.0.0.1 > nul
start /i /w vdesk on:1 run:slack
ping -n 2 127.0.0.1 > nul

start /i /w vdesk on:2 run:devenv2015
start /i /w vdesk noswitch:true on:3 run:sublime_text
exit
```

![thisisperfect](https://user-images.githubusercontent.com/18209220/32589998-0ae35e2e-c540-11e7-894e-cdc664c9e58f.PNG)
> Slack on the _left_ , VS2015 _centre_ , sublime-text-3 to the right. This is perfect 😍 

## Takeaways
1. Wrapping a wait command before and a __volatile command__ seems to achieve the desired effect. Still doesn't work with `noswitch:true` but 🤷‍♂️ 
1.  [___Caution___]In this example, the __volatile command__ is executed right after the `vdesk create:n` command. Only in this case, you need not wait after the create command. In other cases, where you use a normal `vdesk` command first, you need to wait right after that command or, after the create command.
1. This is a super shoddy workaround but it is duct-taped to work and, that matters.

*__volatile command__ : _as referred in this issue_, are those commands, mentioned in the [documentation](https://github.com/eksime/VDesk/blob/master/README.md), that produce undesired results with the `noswitch:true` parameter

> To the developer, this is intended to highlight the importance of a `/wait` parameter. Hope to get it in one of the subsequent versions of `vdesk`

> Sharing this just _incase_ someone else needs this in the future. Still want a `/wait` and `/switch:true` [feature](https://github.com/eksime/VDesk/issues/43#issue-272439697) inside `vdesk`

**Comment by eksime** [comment]
I'll look at adding a `wait:` to a future version, it's possible the `element not found` error you encountered to begin with was a result of the 1803 update, which broke previous versions. Try with version 1.2.0 which fixed support for 1803, and re-open an issue if it's still a problem.

As for running .lnk files/shortcuts, it was not a use-case I had considered, although a minimal test of a shortcut  (`C:\Users\User\Desktop\Notepad.exe.lnk`) and `vdesk run:"C:\Users\User\Desktop\Notepad.exe.lnk"` seems to work; however the full path to the .lnk is required.
