### ISSUE TITLE
Needed virtual desktop switcher

### ISSUE THREAD

**Issue by siddhantrimal** [eksime/VDesk#43]
```
vdesk on:2 switch:true
```
This is a feature request

Please add something like this on the next release. Basically, I just want to switch to another Virtual Desktop after running all the necessary commands. As you've mentioned in your doc that chrome, skype and the likes face problems with the `noswitch:true` switch, this could be a workaround.

I've been using a workaround `vdesk on:2 run:temp.bat` which exits as soon as it runs.
```
exit
```
In some cases, I found out that it needs a way to wait. so a `/wait` delimiter would also be appreciated.

Much appreciation for your great work - fellow recent vdesk user

**Comment by eksime** [comment]
Swapping to a virtual desktop can be done using the following:

`vdesk x` 

I had missed it when writing up the documentation, but it should allow you to include it in a batch script after any previous commands.
