### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SamuraiJack** [eksime/VDesk#45]
Hi,

One question - do the virtual desktops, created with this utility, each have own focus and cursor?

I'm trying to parallelize the Selenium tests. Just running them in several parallel processes is not enough, as focus is an exclusive resource, and only one test page can "own" it at a time. So when running several Selenium tests in the same desktop, the focus jumps between them and that messes up the test results.

To workaround, on Linux, I'm using xvfb-run, and that works very well, every process is running in its own X server, having own focus and cursor.

Does VDesk provide same functionality on Windows?

Thanks, Nickolay

**Comment by eksime** [comment]
Unfortunately, they don't have their own focus. They function similarly to multiple monitors really.

You could try sysinternals desktops, which works differently, or possibly multiple RDP sessions to localhost, although that requires either modifying a system dll or using RDS on windows server.
