### ISSUE TITLE
VDesk -install removed?

### ISSUE THREAD

**Issue by AhmetFUsta** [eksime/VDesk#46]
I wanted to add VDesk to the windows context menu because as a commandline its not very practical for me. `vdesk -install` gives a messagebox with the usage so I went back to look at build/release notes and I haven't seen anything about this feature being removed, only added.

**Comment by eksime** [comment]
Hi, vdesk -install was included in a very early build, but was removed until I could finalize a syntax for the command line, and to assess installation options. It's not likely to be added back just yet as it's quite hard to get working reliably with the current syntax. 

It's something I'm aware people want, and although I don't get much time to work on this anymore, is something I will look to re-add in the future.
