### ISSUE TITLE
VDesk doesn't work correctly after windows update

### ISSUE THREAD

**Issue by stratodolph** [eksime/VDesk#51]
Hi eksime,

First, thanks for your work.

2 days ago my windows version was updated (attach version), after this, vdesk has some problems:
![windowsversion](https://user-images.githubusercontent.com/26674788/40168925-1102bc36-59c5-11e8-9e96-3e5041962795.png)
![error2](https://user-images.githubusercontent.com/26674788/40168983-36132e8e-59c5-11e8-8c18-59b0b224c579.png)
![error1](https://user-images.githubusercontent.com/26674788/40168988-39853062-59c5-11e8-9d88-2c2ac41c62d0.png)

If you need something more, please contact me.

Thanks and regards, Javi.

**Comment by OfficialWardog** [comment]
Windows changed how virtual desktops are created and used, virtual desktops are now part of Timeline.

**Comment by Menci** [comment]
Without `noswitch` it runs. But what I need exactly is `noswitch` ...

**Comment by mgyver** [comment]
thanks Menci for your comment ... you can write a simple AHK script to switch back after running VDESK without `noswitch`.

**Comment by eksime** [comment]
Fixed support for 1803 in 8c1bf48, updating to version 1.2.0 should fix this issue without a workaround.
