### ISSUE TITLE
Doesn't work with windows 10 October update

### ISSUE THREAD

**Issue by prkhandelwal** [eksime/VDesk#61]

**Comment by teoxoy** [comment]
Works fine for me.

**Comment by TysonZ** [comment]
I can confirm that it's working as intended in my environment.

**Comment by prkhandelwal** [comment]
Maybe it's an isolated bug. I tried multiple times but I can't get it on my laptop.

**Comment by drgreatscott** [comment]
Using the latest version, I have been getting this error: "Object reference not set to an instance of an object", no matter what args I use. 

All of the following generates the same error message:

vdesk create:2

vdesk on:2 run:notepad.exe

"D:\Program Files (x86)\VDesk\vdesk.exe" on:2 noswitch:true run:"D:\Program Files (x86)\ChatZilla\xulrunner\xulrunner.exe" "D:\Program Files (x86)\ChatZilla\xulrunner\xulrunner.exe" "D:\Program Files (x86)\ChatZilla\application.ini"

Just FYI.

====
Update: now it works after I completely removed and reinstalled vdesk. I tried to fix vdesk installation several times but didn't help. Removing it and reinstalling it helped.
