### ISSUE TITLE
noswitch:true not working

### ISSUE THREAD

**Issue by Alles4Toast** [eksime/VDesk#81]
When running a programm with **vdesk on:n noswitch:true run:command**, the **noswitch** argument overwrites the **on** argument. If **noswitch** is set to _false_ the programm launches on virtual desktop _n_. Otherwise, the programm launches on the current virtual desktop, regardless of the dekstop specified through the **on** operator.

VDesk Version 1.2
OS: Windows 10, Version 2004

**Comment by Alles4Toast** [comment]
A reboot after the initial installation fixed my issue. Programms are still launched on the current desktop and are move to the specified desktop shortly thereafter.

**Comment by iRecords** [comment]
I have the same problem and it persisted after a reboot.
There is a solution?

Vdesk Version 1.2.0
OS: Windows 10 LTSC 21H2 Build 19044.2846
