### ISSUE TITLE
noswitch:true causes error

### ISSUE THREAD

**Issue by Rriggs95** [eksime/VDesk#86]
I am currently running Windows 10 Version 10.0.19042.867 and I installed vdesk using the msi installer of the 1.3 (I think?) version from the releases page.

When I run vdesk with the noswitch:true option I get the following error:

Element not found. (Exception from HRESULT: 0x8002802B (TYPE_E_ELEMENTNOTFOUND))

The launched program then proceeds to open on the currently active desktop, regardless of which desktop I picked with on: n.
From what I can tell, and some experimenting I did, I don't have any other issues with vdesk it works fine other than this one error. Sorry if this is an already active issue.

**Comment by Rriggs95** [comment]
Ok my bad, after some extra experimenting this seems to be an issue specific to the alacritty terminal. Since it's not a general vdesk issue I will close this now

**Comment by kicipu** [comment]
I got this message too:

Element not found. (Exception from HRESULT: 0x8002802B (TYPE_E_ELEMENTNOTFOUND))

what did I do wrong?


edit:
it seems, the program (aida64) takes too long to full launch, so I can not use noswitch for it.

my solution is:
          vdesk on:2 run:"aida64.exe"
          timeout 8
          vdesk on:1 run:"cmd.exe" /k exit
