### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by sim-liberti** [eksime/VDesk#95]
Hi, I have been trying to use vdesk to open applications but every time I try I get the message error in the title. It happens with every application even if the path I use is correct.
For instance, I'm using:
`vdesk on:2 run:"C:\Program Files\Mozilla Firefox\firefox.exe" `
Am I doing something wrong?

**Comment by cruzer619** [comment]
are you running 32bit windows or 64bit.. normally should be on 64bit and should look like this..

vdesk.exe on:2 run:"C:\Program Files (x86)\Mozilla Firefox\firefox.exe"

**Comment by sim-liberti** [comment]
I'm running 64bit 100%... Don't really know why Firefox is not in the x86 folder tho.
